"""Authlib/Flask-Security major version upgrade

Revision ID: eff60fe2a0b7
Revises: 2cd0b2246a0c
Create Date: 2026-02-19 16:01:19.400915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff60fe2a0b7'
down_revision = '2cd0b2246a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint('fs_uniquifier', ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fs_uniquifier', type_='unique')
        batch_op.drop_column('fs_uniquifier')

    # ### end Alembic commands ###
