#!/bin/sh
echo "POSTINST!"

# Create the required directories.
mkdir -p /opt/backend-learnify/var/run/
mkdir -p /opt/backend-learnify/var/log/
mkdir -p /opt/backend-learnify/config/

# Install the unit file.
cp /opt/backend-learnify/config/backend-learnify.init /etc/init.d/backend-learnify
chmod 755 /etc/init.d/backend-learnify
