#!/bin/sh
echo "POSTINST!"

# Create the required directories.
mkdir -p /opt/server/var/run/
mkdir -p /opt/server/var/log/
mkdir -p /opt/server/config/

# Install the unit file.
cp /opt/server/config/server.init /etc/init.d/server
chmod 755 /etc/init.d/server
