#!/bin/sh
echo "POSTINST!"

# Create the required directories.
mkdir -p /opt/backend/var/run/
mkdir -p /opt/backend/var/log/
mkdir -p /opt/backend/config/

# Install the unit file.
cp /opt/backend/config/backend.init /etc/init.d/backend
chmod 755 /etc/init.d/backend
